"""
CSCI-GA.3033-001: Big Data Application Development
Team Project Code
Cody Gilbert, Fan Han, Jeremy Lao

Holds the constants that define the form selection choices.
"""
STATE_CHOICES = [
                ("01","AL"),
                ("02","AK"),
                ("04","AZ"),
                ("05","AR"),
                ("06","CA"),
                ("08","CO"),
                ("09","CT"),
                ("10","DE"),
                ("12","FL"),
                ("13","GA"),
                ("15","HI"),
                ("16","ID"),
                ("17","IL"),
                ("18","IN"),
                ("19","IA"),
                ("20","KS"),
                ("21","KY"),
                ("22","LA"),
                ("23","ME"),
                ("24","MD"),
                ("25","MD"),
                ("26","MI"),
                ("27","MN"),
                ("28","MS"),
                ("29","MO"),
                ("30","MT"),
                ("31","NE"),
                ("32","NV"),
                ("33","NH"),
                ("34","NJ"),
                ("35","NM"),
                ("36","NY"),
                ("37","NC"),
                ("38","ND"),
                ("39","OH"),
                ("40","OK"),
                ("41","OR"),
                ("42","PA"),
                ("44","RI"),
                ("45","SC"),
                ("46","SD"),
                ("47","TN"),
                ("48","TX"),
                ("49","UT"),
                ("50","VT"),
                ("51","VA"),
                ("53","WA"),
                ("55","WI"),
                ("56","WY"),
                ("60","AS"),
                ("66","GU"),
                ("69","MP"),
                ("72","PR"),
                ("78","VI")]
ETHNICITY = [(1, "Hispanic or Latino"),
             (2, "Not Hispanic or Latino")]
RACE = [(1, "American Indian or Alaska Native"),
        (2, "Asian"),
        (3, "Black or African American"),
        (4, "Native Hawaiian or Other Pacific Islander"),
        (5, "White")]
GENDER = [(1, "Male"),
          (2, "Female")]
